### ISSUE TITLE
Mount /headless with docker-compose

### ISSUE THREAD

**Issue by McGriddle** [ConSol/docker-headless-vnc-container#113]
**Image**
ubuntu-xfce-vnc

**Tag**
latest

I'm having issues persisting `/headless` using docker-compose.

Here is the error I get
```
sudo docker-compose logs vnc
Attaching to vnc
vnc          | /dockerstartup/vnc_startup.sh: line 38: /headless/.bashrc: No such file or directory
```
docker-compose
```
vnc:
    container_name: vnc
    build: ./vnc/build
    user: 122:1001
    environment:
      - VNC_RESOLUTION=1024x768
    volumes:
      - ./vnc/home:/headless
```

Dockerfile
```
## Custom Dockerfile
FROM consol/ubuntu-xfce-vnc
ENV REFRESHED_AT 2018-03-18

# Switch to root user to install additional software
USER 0

## Install a gedit
RUN apt-get update && \
    apt-get install -y vlc mcomix traceroute nmap iftop htop iotop deluge-gtk gedit unzip zip tar pidgin

## switch back to default user
USER 122
```

I've made sure that the `./vnc/home` exists and is owned by `122:1001`. Heck, I set the directory to 777 just to see if that would help. I've tried having that directory owned by root:root as well.

**Comment by s1hofmann** [comment]
Hi @McGriddle!

My first guess would be that `./vnc/home` is an empty directory?

If so, 
```
volumes:
      - ./vnc/home:/headless
```
does a `bind` mount of an empty directory, overriding the default content of `/headless`.
This causes the `source ~/.bashrc` in `/dockerstartup/vnc_startup.sh` to break, since you removed the file with your `bind` mount.

In case you want to persist your data, you could either use a named volume
```
volumes:
      - home_data:/headless
```
or initially copy the content of `/headless/` to `./vnc/home`

**Comment by McGriddle** [comment]
You are correct it was an empty directory. I had a few (incorrect) notions about path based vs named based volumes. Thanks for the help! 

```
  vnc:
    container_name: vnc
    build: ./vnc/build
    user: 122:1001
    environment:
      - VNC_RESOLUTION=1024x768
    volumes:
      - vnc_home:/headless
#....
volumes:
  vnc_home:
```
