### ISSUE TITLE
How to see graphical apps from other containers?

### ISSUE THREAD

**Issue by rubenanapu** [ConSol/docker-headless-vnc-container#125]
**Image**: consol/ubuntu-xfce-vnc

**Tag**: latest

**Short summary**
In order to see a graphical tool from a container on the host we can easily do something like in the example below:

`docker run   --rm   -it   --net=host   -e DISPLAY   -v $HOME/.Xauthority:/root/.Xauthority   fr3nd/xeyes`

By instead of seeing the graphical tool in my computer (docker host), I'd like to see it on `consol/ubuntu-xfce-vnc`

**So my question is:** Is it possible to see on `consol/ubuntu-xfce-vnc`  a graphical tool launched in a different container? If so, how to achieve that? 

Thanks in advance.

**Comment by rubenanapu** [comment]
I found the solution myself. I couldn't do it before because I was not running the GUI tool with a root user ( `id 0` )

I've created the `docker-compose.yml` file with the following content:

```
version: '3'
services:
  xeyes:
    build: .
    image: gns3/xeyes
    restart: always
    entrypoint: ["/bin/bash", "-c"]
    user: "0"
    volumes:
      - xserver:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=:1
    command:
      - xeyes
    depends_on:
      - vnc
  vnc:
    image: consol/ubuntu-xfce-vnc
    restart: always
    user: "0"
    ports:
      - "6902:6901"
      - "5902:5901"
    volumes:
      - xserver:/tmp/.X11-unix:rw
    command: --debug

volumes:
  xserver:

```

Then I ran  `docker-compose up -d`. After that I connected to http://localhost:6902/ with password `vncpassword` and there `xeyes` (the GUI app) was.

I'll close this issue.
