### ISSUE TITLE
Can not connect to the image via VNC client when deployed as a service in Kubenetes

### ISSUE THREAD

**Issue by conanak99** [ConSol/docker-headless-vnc-container#98]
Hi,

__Short description__: Can not connect to the image via VNC client when deployed as a service in Kubenetes
__Detai__: I'm trying to run a version of `consol/ubuntu-xfce-vnc` container Azure Kubernetes service. The service was run, I can access the NoVNC server successful via port 32001, but I can not VNC to the container via port 32002. (Both ports had been allowed in Azure).

This is the .yaml that I used
```
#### POD config (run one time)
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: headless-vnc
  labels:
    application: headless-vnc
spec:
  # 1 Pods should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        application: headless-vnc
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: headless-vnc
        image: consol/ubuntu-xfce-vnc
        imagePullPolicy: Always
        args:
          ### make normal UI startup to connect via: oc rsh <pod-name> bash
          #- '--tail-log'
        ### checks that vnc server is up and running
        livenessProbe:
          tcpSocket:
            port: 5901
          initialDelaySeconds: 1
          timeoutSeconds: 1
        ### checks if http-vnc connection is working
        readinessProbe:
          httpGet:
            path: /
            port: 6901
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: headless-vnc
  name: headless-vnc
spec:
  externalName: headless-vnc
  ports:
  - name: http-port-tcp
    protocol: TCP
    port: 6901
    targetPort: 6901
    nodePort: 32001
  - name: vnc-port-tcp
    protocol: TCP
    port: 5901
    targetPort: 5901
    nodePort: 32002
  selector:
    application: headless-vnc
  type: NodePort
# Use type loadbalancer if needed
#  type: LoadBalancer
```

When I run the image as a container in Docker, I can access both the NoVNC and connect to VNC Server.

Thanks,
Harry
